### ISSUE TITLE
Start with Web Push

### ISSUE THREAD

**Issue by DFC1990** [webmaxru/node-red-contrib-web-push#6]
Hello everyone, unfortunately I am not getting any push messages in my browser. 
Is there a manual where it is described where I have to enter which scripts so that the browser logs into Node-red WEB-PUSH-API so that I can send notification?

**Comment by bartbutenaers** [comment]
In case you would be using the Node-RED dashboard, you can use the https://github.com/bartbutenaers/node-red-contrib-ui-web-push node.  That node works closely together with Maxim's nodes.  Remark: it is not published on NPM yet.
In case you use another web framework, I don't know how to do it.  Because this repository only contains the Node-RED node, but no client-side service worker script...

**Comment by DFC1990** [comment]
Okay, thank you. I’ll try to install the NPM from GitHub because it isn’t published to NPM now ... 

Do I need Https or is http possible ?

**Comment by bartbutenaers** [comment]
You can install it directly from github like this:
npm install bartbutenaers/node-red-contrib-ui-web-push

Yes as you can see on my readme page you need both https and a signed certificate.  To make the trusted certificate easier, I have developed recently the [node-red-contrib-letsencrypt](https://github.com/bartbutenaers/node-red-contrib-letsencrypt) (also not on npm yet).  I use it in combination with duckdns which works fine.  And if you use Node-RED 1.1 (currently in beta phase) you can - based on my [pull request](https://github.com/node-red/node-red/pull/2551) - reload your renewed letsencrypt certificates into Node-RED without restarting...
